project:
    title: "boxy"
    subtitle: "Facebook-like dialog/overlay, with frills"
    jquery_version: "1.2.3"
    main_nav:
        - ["Overview", "#overview"]
        - ["Downloading", "#downloading"]
        - ["Setup", "#setup"]
        - ["Using the jQuery Plugin", "#jquery-plugin"]
        - ["Creating Instances Manually", "#manual-labour"]
        - ["API", "#api"]
        - ["Constructor Options", "#constructor-options"]
        - ["CSS Selectors", "#css-selectors"]
        - ["TODO", "#todo"]
    stylesheets: ['stylesheets/boxy.css']
    javascripts: ['javascripts/jquery.boxy.js']
